use_frameworks!

platform :ios, '9.0'

target 'MBProgressHUDOfAX_Example' do
  pod 'MBProgressHUDOfAX', :path => '../'

  target 'MBProgressHUDOfAX_Tests' do
    inherit! :search_paths

    
  end
end
